-- CONSULTAS COM FILTRO E OPERADORES LÓGICOS

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND EMBALAGEM = 'PET';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Manga' AND EMBALAGEM = 'Garrafa';

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Cereja/Maca' OR EMBALAGEM = 'PET';


SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR in ('Manga','Cereja/Maca')) AND EMBALAGEM = 'Garrafa';

SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE (CIDADE in ('Sao Paulo')) AND (IDADE BETWEEN 20 AND 25);


