-- CONSULTA COM DISTINCT

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MORANGO';
SELECT DISTINCT EMBALAGEM,SABOR FROM TABELA_DE_PRODUTOS;
