-- CONSULTA COM GROUPBY

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES;


SELECT CIDADE, SUM(IDADE) AS IDADE FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT CIDADE, AVG(IDADE) AS IDADE, ROUND(AVG(LIMITE_DE_CREDITO),2) AS CREDITO
FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT CIDADE, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM;

SELECT COUNT(*) AS QUANTIDADE_TOTAL FROM ITENS_NOTAS_FISCAIS 
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;


