-- CONSULTA COM UNION

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES;
-- 11 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 4 BAIRROS

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
-- 12 BAIRROS

SELECT DISTINCT BAIRRO, 'CLIENTE' AS 'ORIGEM' FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS 'ORIGEM' FROM TABELA_DE_VENDEDORES;
-- 15 BAIRROS

