-- CONSULTA COM FILTRO
SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA > 10;
SELECT COUNT(*) FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA > 10;

SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'Garrafa';

-- FILTRO DE DATA

SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO > '1995-07-25';
SELECT * FROM TABELA_DE_CLIENTES WHERE YEAR(DATA_DE_NASCIMENTO) > '1995';
SELECT * FROM TABELA_DE_CLIENTES WHERE MONTH(DATA_DE_NASCIMENTO) >= '11';

