-- CONSULTA COM LIKE

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Limao';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Maca';
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%Morango';
SELECT * FROM TABELA_DE_PRODUTOS WHERE (SABOR LIKE '%Maca') OR (SABOR LIKE '%Morango');

SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%SILVA';