-- FUNÇÕES DE CONVERSÃO

-- CONVERTER: DATA PARA TEXTO

SELECT CONVERT(VARCHAR(30), GETDATE(),121);

SELECT 
DATA_DE_NASCIMENTO,
CONVERT(VARCHAR(25),DATA_DE_NASCIMENTO,106) AS DATA_TEXTO
FROM TABELA_DE_CLIENTES;


-- CAST: NÚMEROS PARA NÚMEROS
SELECT
NOME_DO_PRODUTO,
CONCAT('O preço de lista é: R$', CAST(PRECO_DE_LISTA AS VARCHAR(10))) AS PRECO
FROM TABELA_DE_PRODUTOS;


-- DESAFIO
-- Construa para cada cliente: "O cliente João da Silva comprou R$ 121222,12 no ano de 2016".

SELECT 
CONCAT(
	'O cliente ',
	TC.NOME,
	' comprou R$',
	TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO),10,2)),
	' no ano de ',
	DATENAME(YEAR, NF.DATA_VENDA)
	)
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, NF.DATA_VENDA;