-- PRÁTICA

-- QUANTIDADE DE VENDAS POR MÊS E CPF
SELECT
NF.CPF,
CONVERT(VARCHAR(7),NF.DATA_VENDA,120) AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY 
NF.CPF,
CONVERT(VARCHAR(7),NF.DATA_VENDA,120);

--VOLUME DE COMPRA TABELA DE CLIENTES
SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;



-- VENDAS EM JANEIRO DE 2015 COM CLASSIFICAÇÃO DE LIMITE DE COMPRA
SELECT 
TC.CPF,TC. NOME, TC.VOLUME_DE_COMPRA, 
TOTAL_VENDA.MES_ANO, TOTAL_VENDA.QUANTIDADE_TOTAL,
(
CASE WHEN TC.VOLUME_DE_COMPRA >= TOTAL_VENDA.QUANTIDADE_TOTAL 
THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END
) AS RESULTADO
FROM TABELA_DE_CLIENTES AS TC
INNER JOIN
(
SELECT
NF.CPF,
CONVERT(VARCHAR(7),NF.DATA_VENDA,120) AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY 
NF.CPF,
CONVERT(VARCHAR(7),NF.DATA_VENDA,120)
) AS TOTAL_VENDA
ON TOTAL_VENDA.CPF = TC.CPF
WHERE TOTAL_VENDA.MES_ANO = '2015-01';


-- DESAFIO 
-- Liste somente os que tiveram vendas inválidas e calcule a diferença entre o limite de venda máximo e o realizado, em percentuais.
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100, 2) AS PERCENTUAL
FROM TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT 
NF.CPF
,CONVERT(VARCHAR(7), NF.DATA_VENDA, 120) AS MES_ANO
,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
NF.CPF
, CONVERT(VARCHAR(7), NF.DATA_VENDA, 120)
) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '2015-01'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;
