-- CONSULTA COM INNER JOIN

SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, COUNT(*) AS NUMERO_NOTAS
FROM NOTAS_FISCAIS GROUP BY MATRICULA;

SELECT NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME, COUNT(*) AS NUMERO_NOTAS
FROM NOTAS_FISCAIS
INNER JOIN TABELA_DE_VENDEDORES
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES.NOME;

SELECT T_NF.MATRICULA, T_V.NOME, COUNT(*) AS NUMERO_NOTAS
FROM NOTAS_FISCAIS T_NF
INNER JOIN TABELA_DE_VENDEDORES T_V
ON T_NF.MATRICULA = T_V.MATRICULA
GROUP BY T_NF.MATRICULA, T_V.NOME;