-- CONSULTAS COM ALIAS

SELECT CPF AS IDENTIFICADOR, NOME AS [NOME DE CLIENTE], BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.CPF, TDC.NOME, TDC.BAIRRO FROM TABELA_DE_CLIENTES TDC;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT TDP.* FROM TABELA_DE_PRODUTOS TDP;

SELECT * FROM NOTAS_FISCAIS NF;

SELECT INF.* FROM ITENS_NOTAS_FISCAIS INF;

