--FUNÇÕES DATA E HORA

SELECT 
GETDATE() AS DATA_ATUAL,
DATEADD(DAY,30,GETDATE()) AS PRAXO_30_DIAS,
DATEDIFF(DAY,'2023-01-01',GETDATE()) AS DIAS_DESDE_O_INICIO_DO_ANO
;


IF ISDATE('1995-07-25') = 1  
    PRINT 'DATA VÁLIDA'  
ELSE  
    PRINT 'DATA INVÁLIDA';  

IF ISDATE('1995-25-07') = 1  -- VALIDA APENAS PADRÃO NORTE-AMERICANO 
    PRINT 'DATA VÁLIDA'  
ELSE  
    PRINT 'DATA INVÁLIDA';  

SELECT 
NOME,
DATA_DE_NASCIMENTO,
CONCAT(
	'Dia', DATENAME(DAY,DATA_DE_NASCIMENTO),
	' (',LOWER(DATENAME(WEEKDAY,DATA_DE_NASCIMENTO)),')',	
	' de ', LOWER(DATENAME(MONTH,DATA_DE_NASCIMENTO)),	
	' de ', DATENAME(YEAR,DATA_DE_NASCIMENTO)
) AS NOME_POR_EXTENSO
FROM TABELA_DE_CLIENTES;

