-- CONSULTAS COM FUNÇÕES DE TEXTO

SELECT * FROM TABELA_DE_CLIENTES;

-- LOWER, UPPER, CONCAT
SELECT 
NOME,
LOWER(NOME) AS NOME_MINUSCULO,
UPPER(NOME) AS NOME_MAIUSCULO,
ENDERECO_1,
CONCAT(ENDERECO_1,', ',BAIRRO,', ',CIDADE,'-',ESTADO,'; CEP:',CEP) AS ENDERECO_COMPLETO
FROM 
TABELA_DE_CLIENTES;

--LEFT,RIGHT

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT
EMBALAGEM,
LEFT(EMBALAGEM,3) AS TRES_PRIMEIROS_CHAR,
RIGHT(EMBALAGEM,3) AS TRES_ULTIMOS_CHAR,
NOME_DO_PRODUTO,
REPLACE(REPLACE(NOME_DO_PRODUTO, 'LITROS', 'L'), 'LITRO', 'L') AS NOME_DO_PRODUTO_COM_TAMANHO_MODIFICADO
FROM
TABELA_DE_PRODUTOS;

--EXERCÍCIO
-- Faça uma consulta que traga somente o primeiro nome de cada cliente.


SELECT NOME, 
SUBSTRING(NOME,1,CHARINDEX(' ', NOME, 1)) AS PRIMEIRO_NOME,
TRIM(SUBSTRING(NOME, CHARINDEX(' ', NOME), LEN(NOME))) AS SOBRENOME
FROM TABELA_DE_CLIENTES;




















