-- CONSULTA COM HAVING

SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO
FROM TABELA_DE_CLIENTES GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;


SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >=10;


SELECT * FROM ITENS_NOTAS_FISCAIS;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE_DE_VENDAS
FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO
ORDER BY QUANTIDADE_DE_VENDAS DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE_DE_VENDAS
FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY QUANTIDADE_DE_VENDAS DESC;